// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyARQreWud8m7YpkR4fEQ2xt3svErcQrYD8',
    appId: '1:721414446237:web:cdec509cca439bc2130874',
    messagingSenderId: '721414446237',
    projectId: 'appfit-ecae4',
    authDomain: 'appfit-ecae4.firebaseapp.com',
    storageBucket: 'appfit-ecae4.firebasestorage.app',
    measurementId: 'G-DZSSRF0C32',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCVvzHZuYbb5kDsaIDHP9bOfrF1G6fH1tM',
    appId: '1:721414446237:android:17f8566fbca77268130874',
    messagingSenderId: '721414446237',
    projectId: 'appfit-ecae4',
    storageBucket: 'appfit-ecae4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC42apgwOLCu_38fXjf62trl0EsvbTQ3Cs',
    appId: '1:721414446237:ios:db30cd2027fa9e54130874',
    messagingSenderId: '721414446237',
    projectId: 'appfit-ecae4',
    storageBucket: 'appfit-ecae4.firebasestorage.app',
    iosBundleId: 'com.example.lifetrack',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC42apgwOLCu_38fXjf62trl0EsvbTQ3Cs',
    appId: '1:721414446237:ios:db30cd2027fa9e54130874',
    messagingSenderId: '721414446237',
    projectId: 'appfit-ecae4',
    storageBucket: 'appfit-ecae4.firebasestorage.app',
    iosBundleId: 'com.example.lifetrack',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyARQreWud8m7YpkR4fEQ2xt3svErcQrYD8',
    appId: '1:721414446237:web:9aa0c3edd76726e2130874',
    messagingSenderId: '721414446237',
    projectId: 'appfit-ecae4',
    authDomain: 'appfit-ecae4.firebaseapp.com',
    storageBucket: 'appfit-ecae4.firebasestorage.app',
    measurementId: 'G-449Q87C1BG',
  );
}
